import Image from "next/image";
import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,ArrowUpRight,Check} from "lucide-react";
import {projects} from "@/lib/portfolio";
import {SITE_URL} from "@/lib/site";
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);return {title:p?`${p.name} Case Study`:"Project not found",description:p?.summary,alternates:{canonical:`/projects/${slug}`},openGraph:p?{title:`${p.name} | Sandeep Dusadh`,description:p.summary,url:`${SITE_URL}/projects/${slug}`,type:"article" as const}:undefined}}
export default async function ProjectDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);if(!p)notFound();const next=projects[(projects.findIndex(x=>x.slug===slug)+1)%projects.length];return <>
<section className={`case-hero accent-${p.accent}`}><div className="container"><Link className="back-link" href="/projects"><ArrowLeft size={17}/> All projects</Link><div className="case-header"><div><span className="eyebrow">{p.category.toUpperCase()} / {p.year}</span><h1>{p.name}<span className="title-dot">.</span></h1><p>{p.summary}</p></div><div className="case-symbol" aria-hidden="true">{p.symbol}</div></div><div className="case-meta"><span><small>STAGE</small>{p.status}</span><span><small>BUILT FOR</small>{p.audience||"A future product audience"}</span><span><small>MY ROLE</small>{p.contribution||"Product research and concept design"}</span></div></div></section>
{p.screenshots?.length&&<section className="section container case-gallery"><div className="section-top"><div><span className="eyebrow">THE INTERFACE / REAL CAPTURES</span><h2>See the work.</h2></div><p className="section-intro">Actual screens from working site previews and an earlier desktop demo. Each caption explains the project stage.</p></div><div className="screenshot-grid">{p.screenshots.map((screen,i)=><figure key={screen.src} className={i===0?"screenshot featured":"screenshot"}><div className={`screenshot-viewport ${p.slug==="pharmacy-desk"?"desktop-shot":"website-shot"}`}><Image src={screen.src} alt={screen.alt} width={1920} height={1080} unoptimized/></div><figcaption><span>{String(i+1).padStart(2,"0")}</span>{screen.caption}</figcaption></figure>)}</div></section>}
<section className="section container case-body"><div className="case-side"><span className="eyebrow">THE PROJECT STORY</span><h2>What it solves.<br/>How it works.</h2></div><div className="case-copy"><article><span>01 / THE PEOPLE</span><h3>Who it is for</h3><p>{p.audience||"This idea is still defining its audience."}</p></article><article><span>02 / THE PROBLEM</span><h3>What needed solving</h3><p>{p.challenge}</p></article><article><span>03 / MY CONTRIBUTION</span><h3>What I worked on</h3><p>{p.contribution||"Product research and concept definition."} {p.approach}</p></article><article><span>04 / THE STATUS</span><h3>Where it stands</h3><p>{p.result}</p></article><article><span>05 / THE NEXT STEP</span><h3>What comes next</h3><p>{p.nextStep||"Validate the concept and scope before starting implementation."}</p></article></div></section>
<section className="section statement-section"><div className="container detail-grid"><div><span className="eyebrow">WORKFLOWS & FEATURES</span><h2>Inside the build.</h2><div className="feature-list">{p.features.map(f=><div key={f}><Check size={18}/>{f}</div>)}</div></div><div><span className="eyebrow">CLIENT VALUE & STACK</span><h2>Why it matters.</h2><p className="case-value">{p.value||"A product question to validate before turning this concept into a build."}</p><div className="stack-tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div><p className="stage-note">Stage: {p.status}. A screenshot documents an interface; it does not claim a finished deployment, verified results or a client rollout.</p></div></div></section><section className="next-project container"><span className="eyebrow">NEXT PROJECT</span><Link href={`/projects/${next.slug}`}>{next.name} <ArrowUpRight size={35}/></Link></section></>}
