import Link from "next/link";
import {ArrowDown,ArrowUpRight,Code2,Database,Layers3} from "lucide-react";
import ProjectCard from "@/components/portfolio/ProjectCard";
import {projects} from "@/lib/portfolio";
export const metadata={title:{absolute:"Sandeep Dusadh | Full-Stack Developer in Mumbai"},description:"Sandeep Dusadh builds Vue, React and Nuxt interfaces, Python FastAPI backends, and practical business software. See ClipVexa, UniversalFetch, PharmacyDesk and TrustLens.",alternates:{canonical:"/"}};
export default function Home(){return <>
<section className="home-hero professional-hero"><div className="hero-image" aria-hidden="true"/><div className="hero-shade"/><div className="hero-content container"><span className="eyebrow hero-kicker">SANDEEP DUSADH / FULL-STACK DEVELOPER</span><h1>I build web apps<br/><em>that work for you.</em></h1><p className="hero-lead">Full-stack development for businesses with a problem to solve: responsive React, Vue and Nuxt interfaces, Python FastAPI services and practical business software.</p><div className="hero-buttons"><Link className="button" href="/projects">Explore my work <ArrowUpRight size={18}/></Link><Link className="button outline" href="/contact">Let&apos;s talk <ArrowUpRight size={18}/></Link></div><div className="hero-specialties"><span>02+ YEARS IN FULL-STACK DEVELOPMENT</span><span>MUMBAI · REMOTE READY</span></div><div className="hero-profile-links"><a href="https://www.linkedin.com/in/sandeep-dusadh-11089a1b6/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/Martin1496" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="/SandeepDusadh_Resume.pdf" download="SandeepDusadh_Resume.pdf">Download résumé ↓</a></div></div><Link className="hero-scroll" href="#featured" aria-label="Scroll to selected projects"><ArrowDown size={18}/><span>SELECTED WORK</span></Link></section>
<section className="credibility-strip"><div className="container"><span>WHAT CLIENTS NEED TO KNOW</span><p>I&apos;ve built production FastAPI services and Vue dashboards, and I document the stage of every independent project honestly.</p><Link href="/about">About my experience <ArrowUpRight size={17}/></Link></div></section>
<section className="home-experience container"><div><span className="eyebrow">PROFESSIONAL EXPERIENCE</span><h2>2+ years building<br/><em>production software.</em></h2></div><div className="experience-detail"><strong>Full-Stack Developer · Symbolist Technology</strong><span>APR 2024 — APR 2026</span><p>Built FastAPI campaign services, email validation, Vue dashboards and MySQL-backed workflows, with OAuth-based access and Docker deployments.</p><Link className="quiet-link" href="/about">See my background <ArrowUpRight size={17}/></Link></div></section><section className="section container" id="featured"><div className="section-top"><div><span className="eyebrow">01 / SELECTED PROJECTS</span><h2>Working screens.<br/><em>Clear project stages.</em></h2></div><p className="section-intro">Website screens from running development builds and an earlier desktop demo, paired with what each project does and what still needs work.</p></div><div className="project-grid showcase-grid">{projects.slice(0,4).map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</div><div className="showcase-next"><span className="eyebrow">WHAT&apos;S NEXT</span><h3>Dog Walk & Before You Buy</h3><p>Ideas in research and planning. They&apos;re separated from working interfaces so you can see exactly what exists today.</p><Link className="quiet-link" href="/projects">Explore all projects <ArrowUpRight size={18}/></Link></div></section>
<section className="section statement-section"><div className="container"><div className="section-top"><div><span className="eyebrow">02 / WHAT I CAN BUILD</span><h2>One developer.<br/><em>Across the stack.</em></h2></div><p className="section-intro">From a customer portal or internal dashboard to an offline billing workflow, I build around how people actually use the product.</p></div><div className="client-services"><article><Code2/><span>01 / FRONTEND</span><h3>Websites & product UI</h3><p>Responsive React, Vue, and Nuxt experiences with useful navigation, clear states and detail across screen sizes.</p><Link href="/services">See the scope <ArrowUpRight size={16}/></Link></article><article><Database/><span>02 / BACKEND</span><h3>Python APIs & integrations</h3><p>FastAPI services, data models, authentication and integrations that support real product workflows.</p><Link href="/services">See the scope <ArrowUpRight size={16}/></Link></article><article><Layers3/><span>03 / BUSINESS SOFTWARE</span><h3>Software for daily work</h3><p>Dashboards, offline processes, inventory and billing flows that help a team get important work done.</p><Link href="/services">See the scope <ArrowUpRight size={16}/></Link></article><article className="service-proof"><span>WORKING EXPERIENCE</span><h3>Built for actual users.</h3><p>At Symbolist Technology, I worked on campaign APIs, email validation, role-based access, responsive Vue dashboards and Docker-based delivery.</p><Link href="/about">Read my background <ArrowUpRight size={16}/></Link></article></div></div></section>
<section className="section container"><div className="section-top"><div><span className="eyebrow">03 / HOW WE WORK</span><h2>Clear from day one.</h2></div><p className="section-intro">A clear scope, reviewable stages, careful testing and a usable handoff. You know what happens after we start.</p></div><div className="delivery-list"><div><b>01</b><h3>Define</h3><p>Map users, the main workflow, constraints and a realistic first release.</p><small>OUTPUT · A focused plan</small></div><div><b>02</b><h3>Build</h3><p>Develop the interface and systems in reviewable stages with regular feedback.</p><small>OUTPUT · Working increments</small></div><div><b>03</b><h3>Deliver</h3><p>Check core journeys, mobile behavior, deployment and handoff details.</p><small>OUTPUT · A release checklist</small></div></div></section>
<section className="about-teaser"><div className="container"><div><span className="eyebrow">ABOUT THE DEVELOPER</span><h2>Real experience.<br/><em>Curious by default.</em></h2></div><div><p>I&apos;m Sandeep, a Mumbai-based full-stack developer with 2+ years of hands-on experience. My core work connects web interfaces, Python APIs and data into products that people can actually use.</p><Link className="quiet-link" href="/about">Meet Sandeep <ArrowUpRight size={18}/></Link></div></div></section>
<section className="cta-panel container"><span className="eyebrow">HAVE A PROJECT IN MIND?</span><h2>Let&apos;s make it useful.</h2><p>Tell me who it&apos;s for and what needs to happen. We can start with a clear scope and build from there.</p><Link className="button" href="/contact">Start a conversation <ArrowUpRight size={18}/></Link></section>
</>}
