"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useEffect,useState} from "react";
import {ArrowUpRight,Menu,X} from "lucide-react";
const nav=[{label:"Home",href:"/"},{label:"Projects",href:"/projects"},{label:"Services",href:"/services"},{label:"Tools & stack",href:"/tools"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}];
export default function SiteShell({children}:{children:React.ReactNode}){
 const path=usePathname(),[open,setOpen]=useState(false),[progress,setProgress]=useState(0);
 useEffect(()=>{window.scrollTo({top:0,behavior:"auto"});document.documentElement.classList.add("js-motion");const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));return()=>observer.disconnect()},[path]);
 useEffect(()=>{const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;setProgress(max>0?scrollY/max*100:0)};addEventListener("scroll",update,{passive:true});update();return()=>removeEventListener("scroll",update)},[path]);
 return <div className={path==="/"?"site home-site":"site"}><div className="scroll-progress" style={{width:`${progress}%`}} aria-hidden="true"/><header className="site-header"><Link href="/" className="brand" aria-label="Sandeep Dusadh home"><span className="brand-glyph">SD<span>.</span></span></Link><nav className={open?"nav open":"nav"} aria-label="Main navigation">{nav.map((item,i)=><Link onClick={()=>setOpen(false)} aria-current={path===item.href?"page":undefined} key={item.href} href={item.href}><small>0{i+1}</small>{item.label}</Link>)}</nav><Link href="/contact" className="button header-cta">Start a project <ArrowUpRight size={18}/></Link><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?"Close menu":"Open menu"}>{open?<X/>:<Menu/>}</button></header><main key={path} className="page-enter">{children}</main><footer className="footer"><div><Link className="footer-logo" href="/">SD<span>.</span></Link><p>Design-minded full-stack development.<br/>Based in Mumbai, working across the web.</p></div><div><span className="footer-title">EXPLORE</span><Link href="/projects">Projects</Link><Link href="/services">Services</Link><Link href="/tools">Tools & stack</Link></div><div><span className="footer-title">CONNECT</span><Link href="/about">About</Link><Link href="/contact">Contact</Link><a href="mailto:sandeepdusadh07@gmail.com">Email</a><a href="https://www.linkedin.com/in/sandeep-dusadh-11089a1b6/" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://github.com/Martin1496" target="_blank" rel="noopener noreferrer">GitHub</a></div><div className="footer-bottom">© {new Date().getFullYear()} Sandeep Dusadh. Crafted with care.</div></footer></div>
}
